# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'ColorLetter' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
pod 'YYWebImage', '~> 1.0.5'
  # Pods for ColorLetter
  pod 'Masonry', '~> 1.0.2'
  pod 'HyphenateFullSDK', '~> 3.1.5'
  pod 'AVOSCloud', '~> 3.6.1'
  pod 'FMDB', '~> 2.6.2'
  pod 'BaiduMapKit'
  pod 'TSMessages', '~> 0.9.12'
end

